#include <vector>
#include <utility>

#include "engine/common/tracelog.hpp"
#include "engine/scripting/bindings/bindings_list.hpp"
#include "engine/scripting/bindings/script_binding_class.hpp"
#include "engine/scripting/bindings/stl_vector_binder.hpp"
#include <bindings/binding_registry.hpp>

namespace CE::Scripting::Bindings {
    class ScriptBindings::Impl {
        public:
            AutoGeneratedBindings mBindings;
            std::vector<std::unique_ptr<IScriptBinding>> mScriptBindings;
    };

    ScriptBindings::~ScriptBindings() {
        delete mImpl;
    }

    bool ScriptBindings::RegisterAllBindings(asIScriptEngine& script_engine, Runtime& runtime) {
        mImpl = new(Impl);
        script_engine.SetDefaultNamespace("CE::Containers");
        RegisterVector<asUINT>(&script_engine, "Uint32Vector", "uint32");
        script_engine.SetDefaultNamespace("");

        for (const auto& entry : mImpl->mBindings.bindings) {
            auto binding = entry.create(runtime, script_engine);
            
            if (!binding->RegisterBindings()) {
                CE_LOG(LogLevel::Error, "[Angelscript] Failed to bind: {}", entry.name);
                return false;
            }

            mImpl->mScriptBindings.push_back(std::move(binding));
        }
        
        return true;
    }
} // namespace CE::Scripting::Bindings