#pragma once

#include <string>

namespace CE::Utils {
    template<typename T>
    std::string EnumToString();
}

/*
 * auto generated by build.py
 * for actual implimentation look inside include/engine/compilers
*/
#include <enum_to_string_impl.inl>