#!/usr/bin/env python3
from __future__ import annotations

import json
import sys
from pathlib import Path


def load_bindings(bindings_dir: Path) -> list[tuple[int, str]]:
    entries: list[tuple[int, str]] = []

    for metadata_path in sorted(bindings_dir.glob("*.generated.json")):
        try:
            data = json.loads(metadata_path.read_text(encoding="utf-8"))
        except json.JSONDecodeError as exc:  # pragma: no cover - surfaced as a real build error
            raise RuntimeError(f"Invalid generated binding metadata: {metadata_path}: {exc}") from exc

        class_name = data.get("class")
        if not class_name:
            continue

        entries.append((int(data.get("registration_priority", 0)), str(class_name)))

    entries.sort(key=lambda item: (-item[0], item[1]))
    return entries


def render_registry(bindings_dir: Path) -> str:
    generated_headers = sorted(bindings_dir.glob("*.generated.hpp"))
    bindings = load_bindings(bindings_dir)

    include_lines = "\n".join(f'#include "{header.name}"' for header in generated_headers)
    if include_lines:
        include_lines += "\n"

    if not bindings:
        bindings_array = "std::array<Entry, 0> bindings = {};"
    else:
        lines = ["std::array<Entry, %d> bindings = {{" % len(bindings)]
        for index, (_, class_name) in enumerate(bindings):
            suffix = "," if index + 1 < len(bindings) else ""
            lines.append("    {")
            lines.append(f'        "{class_name}",')
            lines.append("        [](Runtime& runtime, asIScriptEngine& engine) -> std::unique_ptr<IScriptBinding>")
            lines.append("        {")
            lines.append(f"            return std::make_unique<{class_name}>(runtime, engine);")
            lines.append("        }")
            lines.append(f"    }}{suffix}")
        lines.append("}};")
        bindings_array = "\n".join(lines)

    return f'''#pragma once

#include <array>
#include <memory>
#include <string_view>
#include <angelscript.h>

#include "engine/scripting/bindings/script_binding_class.hpp"
#include "engine/scripting/angelscript.hpp"

{include_lines}
namespace CE::Scripting::Bindings {{

struct AutoGeneratedBindings {{
    struct Entry {{
        std::string_view name;
        std::unique_ptr<IScriptBinding> (*create)(Runtime&, asIScriptEngine&);
    }};

    {bindings_array}
}};

}} // namespace CE::Scripting::Bindings
'''


def main() -> int:
    if len(sys.argv) != 2:
        print(f"Usage: {Path(sys.argv[0]).name} <bindings_dir>", file=sys.stderr)
        return 2

    bindings_dir = Path(sys.argv[1]).resolve()
    bindings_dir.mkdir(parents=True, exist_ok=True)

    output_path = bindings_dir / "binding_registry.hpp"
    output_path.write_text(render_registry(bindings_dir), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
