
file(GLOB_RECURSE SOURCES CONFIGURE_DEPENDS
    "${CE_RUNTIME_SOURCE_DIR}/*.cpp"
    "${CE_RUNTIME_SOURCE_DIR}/*.c"
    "${CE_RUNTIME_SOURCE_DIR}/*/*.cpp"
    "${CE_RUNTIME_SOURCE_DIR}/*/*.c"
)

file(GLOB CE_SHADER_SOURCES CONFIGURE_DEPENDS
    "${CE_RUNTIME_ROOT}/shaders/*.frag"
    "${CE_RUNTIME_ROOT}/shaders/*.vert"
)

file(GLOB_RECURSE CE_ASSET_INPUTS CONFIGURE_DEPENDS
    "${CMAKE_SOURCE_DIR}/assets/*"
)

file(GLOB_RECURSE CE_JSON_ASSET_INPUTS CONFIGURE_DEPENDS
    "${CMAKE_SOURCE_DIR}/assets/*.json"
)

file(GLOB_RECURSE CE_IDL_INPUTS CONFIGURE_DEPENDS
    "${CE_RUNTIME_ROOT}/include/*.idl.yaml"
    "${CE_RUNTIME_SOURCE_DIR}/*.idl.yaml"
    "${CE_RUNTIME_SOURCE_DIR}/*/*.idl.yaml"
)
